camunda.bpm.admin-user:
  id: admin
  password: admin

server.port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: sa
    username: sa
    url: jdbc:h2:mem:pizza
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
